name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x] #ini pake beberapa versi nodejs sekaligus

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }} #ambil version dari variabel node-version di atas

    - run: npm install
    - run: npm run build --if-present #menjalankan script build yang terdefinisi di package.json
    - run: npm test #test npm, ini akan dijalankan kalo ada di script package.json
    - run: npm start &
    - run: sleep 5
    - run: curl -X POST -H "Content-Type:application/json" http://localhost:4000/messages -d '{"text":"Hi again, Des"}' #ini kaya buat post baru jadi akan muncul endpoint di actions pas proses build
    - run: curl http://localhost:4000/messages #lihat massagenya
    - run: curl -X DELETE http://localhost:4000/messages/2 #menghapus massage ke2
    - run: curl http://localhost:4000/messages #lihat massagenya lagi untuk verifikasi
